/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5r2hOIjCo38
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Categories } from "../native/categories/categories";
import { Filters } from "../native/filters/filters";
import ProductsList from "../native/products/productsList";
import { PaginationProducts } from './pagination';



interface Props {
   title: string;
   description: string;

}




export function ProductsByPet({title,description}:Props) {
  const products = [
    {
      name: "Producto 1",
      price: "$19.99",
      description: "Descripción del Producto",
      image:
        "https://res.cloudinary.com/dftvxcvfw/image/upload/v1713359989/products/vsririqv6aldivisv814.jpg",
      link: "#",
    },
    {
      name: "Producto 3",
      price: "$14.99",
      description: "Descripción del Producto",
      image: "/placeholder.svg",
      link: "#",
    },
  ];

  const categories = [
    {
      name: "Alimentos",
      subcategories: ["Secos", "Húmedos", "Snacks"],
    },
    {
      name: "Accesorios",
      subcategories: ["Correas", "Collares", "Juguetes"],
    },
    {
      name: "Higiene",
      subcategories: ["Shampoo", "Cepillos", "Perfumes"],
    },
  ];
  return (
    <div className="container mx-auto grid grid-cols-1 md:grid-cols-[240px_1fr] gap-8 px-4 md:px-6 py-12 md:py-24">
      <div className="md:flex md:flex-col gap-6  hidden">
        <Categories categories={categories} />
        <Filters />
      </div>
      <div className="grid gap-8">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              {title}
            </h2>
            <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              {description}
            </p>
          </div>
          <ProductsList products={products} />
        </div>
        <PaginationProducts/>
      </div>
    </div>
  );
}

